# Site settings
title: Ninject Features
email: urs.enzler@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ninject features extends Ninject so that you can build modular .net applications.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.github.com/ursenzler/ninject.features" # the base hostname & protocol for your site
twitter_username: ursenzler
github_username:  ursenzler
projecturl: "https://www.github.com/ursenzler/ninject.features"
nuget_features: "https://www.nuget.org/packages/Ninject.Features/"
nuget_dumper: "https://www.nuget.org/packages/Ninject.FeatureDumper/"

# Build settings
markdown: kramdown
